name: Build with Bun

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.26
          cache: "npm"
      - run: bun install
      - run: bun build
      - run: bun start
