name: Build with Bun

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
      EMAIL: ${{ secrets.EMAIL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
      JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.26
      - run: bun install
      - run: npm run build
      - run: npm run start
